import { Deal, Contact, Product, PipelineStage } from '@/types/pipeline';

// Mock product images (using placeholder)
const PRODUCT_IMAGES = [
  'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=100&h=100&fit=crop',
  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop',
  'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=100&h=100&fit=crop',
  'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=100&h=100&fit=crop',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop',
];

const contacts: Contact[] = [
  { id: 'c1', name: 'David Martinez', initials: 'DM' },
  { id: 'c2', name: 'Emily Davis', initials: 'ED' },
  { id: 'c3', name: 'Michael Chen', initials: 'MC' },
  { id: 'c4', name: 'Jessica Martinez', initials: 'JM' },
  { id: 'c5', name: 'Sarah Johnson', initials: 'SJ' },
  { id: 'c6', name: 'Robert Williams', initials: 'RW' },
  { id: 'c7', name: 'Daniel Kim', initials: 'DK' },
  { id: 'c8', name: 'James Anderson', initials: 'JA' },
  { id: 'c9', name: 'Amanda Wilson', initials: 'AW' },
  { id: 'c10', name: 'Robert Taylor', initials: 'RT' },
];

const products: Product[] = [
  { id: 'p1', name: 'Tag Heuer Carrera Calibre 16', quantity: 1, price: 4800, imageUrl: PRODUCT_IMAGES[0], supplier: 'Precision Time' },
  { id: 'p2', name: 'Omega Seamaster Diver 300M', quantity: 2, price: 12400, imageUrl: PRODUCT_IMAGES[1], supplier: 'Tourbillon Boutique' },
  { id: 'p3', name: 'Omega Nato Strap', quantity: 2, price: 560, imageUrl: PRODUCT_IMAGES[2], supplier: 'Tourbillon Boutique' },
  { id: 'p4', name: 'AP Royal Oak Chronograph', quantity: 1, price: 52000, imageUrl: PRODUCT_IMAGES[3], supplier: 'Timepiece Gallery' },
  { id: 'p5', name: 'AP Rubber Strap', quantity: 1, price: 850, imageUrl: PRODUCT_IMAGES[4], supplier: 'Timepiece Gallery' },
  { id: 'p6', name: 'Rolex Submariner Date 41mm', quantity: 1, price: 14800, imageUrl: PRODUCT_IMAGES[0], supplier: 'Swiss Watch Connection' },
  { id: 'p7', name: 'Leather Watch Roll Case', quantity: 1, price: 450, imageUrl: PRODUCT_IMAGES[1] },
  { id: 'p8', name: 'Patek Philippe Nautilus 5711', quantity: 1, price: 89500, imageUrl: PRODUCT_IMAGES[2], supplier: 'Luxury Timepieces HK' },
  { id: 'p9', name: 'Patek Philippe Steel Bracelet', quantity: 1, price: 3200, imageUrl: PRODUCT_IMAGES[3], supplier: 'Hong Kong Lux Parts' },
  { id: 'p10', name: 'Premium Watch Winder Box', quantity: 1, price: 890, imageUrl: PRODUCT_IMAGES[4] },
  { id: 'p11', name: 'Rolex Datejust 41 Two-Tone', quantity: 1, price: 13400, imageUrl: PRODUCT_IMAGES[0], supplier: 'Swiss Watch Connection' },
  { id: 'p12', name: 'Omega Speedmaster Moonwatch', quantity: 1, price: 6800, imageUrl: PRODUCT_IMAGES[1], supplier: 'Crown & Caliber' },
  { id: 'p13', name: 'Breitling Navitimer B01 Chrono', quantity: 1, price: 9200, imageUrl: PRODUCT_IMAGES[2], supplier: 'Aviation Watches' },
];

export const mockDeals: Deal[] = [
  // LEADS
  {
    id: 'd1',
    masterOrderNumber: 'MON-2025-101',
    stage: 'leads',
    contact: contacts[0],
    interestedProducts: [{ ...products[0], quantity: 1 }],
    estimatedBudget: 35000,
    totalValue: 0,
    margin: 0,
    marginPercentage: 0,
    tradeInCredit: 0,
    paid: 0,
    totalPaid: 0,
    shipDate: '',
    badges: [],
    productsCount: 0,
  },
  {
    id: 'd2',
    masterOrderNumber: 'MON-2025-102',
    stage: 'leads',
    contact: contacts[1],
    interestedProducts: [{ ...products[1], quantity: 1 }],
    estimatedBudget: 75000,
    totalValue: 0,
    margin: 0,
    marginPercentage: 0,
    tradeInCredit: 0,
    paid: 0,
    totalPaid: 0,
    shipDate: '',
    badges: [],
    productsCount: 0,
  },
  {
    id: 'd3',
    masterOrderNumber: 'MON-2025-103',
    stage: 'leads',
    contact: contacts[5],
    interestedProducts: [{ ...products[3], quantity: 1 }],
    estimatedBudget: 55000,
    totalValue: 0,
    margin: 0,
    marginPercentage: 0,
    tradeInCredit: 0,
    paid: 0,
    totalPaid: 0,
    shipDate: '',
    badges: [],
    productsCount: 0,
  },

  // FIRST CONTACT
  {
    id: 'd4',
    masterOrderNumber: 'MON-2025-003',
    stage: 'first-contact',
    contact: contacts[1],
    interestedProducts: [{ ...products[0], quantity: 1 }],
    estimatedBudget: 0,
    totalValue: 4800,
    margin: 1200,
    marginPercentage: 25,
    tradeInCredit: 0,
    paid: 0,
    totalPaid: 4800,
    shipDate: '2025-12-10',
    badges: ['DOM'],
    productsCount: 1,
  },

  // NEGOTIATION
  {
    id: 'd5',
    masterOrderNumber: 'MON-2025-002',
    stage: 'negotiation',
    contact: contacts[2],
    interestedProducts: [
      { ...products[1], quantity: 2 },
      { ...products[2], quantity: 2 },
    ],
    estimatedBudget: 0,
    totalValue: 12960,
    margin: 3120,
    marginPercentage: 24,
    tradeInCredit: -1800,
    paid: 0,
    totalPaid: 11160,
    shipDate: '2025-11-30',
    badges: ['HK'],
    productsCount: 2,
  },
  {
    id: 'd6',
    masterOrderNumber: 'MON-2025-004',
    stage: 'negotiation',
    contact: contacts[6],
    interestedProducts: [
      { ...products[7], quantity: 1 },
      { ...products[8], quantity: 1 },
      { ...products[9], quantity: 1 },
    ],
    estimatedBudget: 0,
    totalValue: 93590,
    margin: 16040,
    marginPercentage: 17,
    tradeInCredit: 0,
    paid: 0,
    totalPaid: 93590,
    shipDate: '',
    badges: ['HK', 'DROPSHIP'],
    productsCount: 3,
  },

  // INVOICE
  {
    id: 'd7',
    masterOrderNumber: 'MON-2025-005',
    stage: 'invoice',
    contact: contacts[3],
    interestedProducts: [
      { ...products[3], quantity: 1 },
      { ...products[4], quantity: 1 },
    ],
    estimatedBudget: 0,
    totalValue: 52850,
    margin: 8470,
    marginPercentage: 16,
    tradeInCredit: -4800,
    paid: 38000,
    totalPaid: 48050,
    shipDate: '2025-11-25',
    badges: ['DOM'],
    productsCount: 2,
  },

  // PAID
  {
    id: 'd8',
    masterOrderNumber: 'MON-2025-001',
    stage: 'paid',
    contact: contacts[4],
    interestedProducts: [
      { ...products[5], quantity: 1 },
      { ...products[6], quantity: 1 },
    ],
    estimatedBudget: 0,
    totalValue: 15250,
    margin: 2830,
    marginPercentage: 19,
    tradeInCredit: 0,
    paid: 7500,
    totalPaid: 15250,
    shipDate: '2025-11-15',
    badges: ['HK', 'DROPSHIP'],
    productsCount: 2,
  },

  // CLOSED
  {
    id: 'd9',
    masterOrderNumber: 'MON-2025-008',
    stage: 'closed',
    contact: contacts[7],
    interestedProducts: [{ ...products[10], quantity: 1 }],
    estimatedBudget: 0,
    totalValue: 13400,
    margin: 2600,
    marginPercentage: 19,
    tradeInCredit: 0,
    paid: 13400,
    totalPaid: 13400,
    shipDate: '2025-10-28',
    badges: ['HK', 'DROPSHIP'],
    productsCount: 1,
  },

  // DEAD
  {
    id: 'd10',
    masterOrderNumber: 'MON-2025-007',
    stage: 'dead',
    contact: contacts[8],
    interestedProducts: [{ ...products[11], quantity: 1 }],
    estimatedBudget: 0,
    totalValue: 6800,
    margin: 1600,
    marginPercentage: 24,
    tradeInCredit: 0,
    paid: 0,
    totalPaid: 6800,
    shipDate: '2025-12-15',
    badges: ['DOM'],
    productsCount: 1,
  },

  // FOLLOW-UP
  {
    id: 'd11',
    masterOrderNumber: 'MON-2025-006',
    stage: 'follow-up',
    contact: contacts[9],
    interestedProducts: [{ ...products[12], quantity: 1 }],
    estimatedBudget: 0,
    totalValue: 9200,
    margin: 2100,
    marginPercentage: 23,
    tradeInCredit: 0,
    paid: 0,
    totalPaid: 9200,
    shipDate: '2025-12-05',
    badges: ['DOM'],
    productsCount: 1,
  },
];

export const pipelineStages: { id: PipelineStage; title: string }[] = [
  { id: 'leads', title: 'Leads' },
  { id: 'first-contact', title: 'First Contact' },
  { id: 'negotiation', title: 'Negotiation' },
  { id: 'invoice', title: 'Invoice' },
  { id: 'paid', title: 'Paid' },
  { id: 'product-sourced', title: 'Product Sourced' },
  { id: 'awaiting-shipment', title: 'Awaiting Shipment' },
  { id: 'ready-to-ship', title: 'Ready to Ship' },
  { id: 'shipped', title: 'Shipped' },
  { id: 'closed', title: 'Closed' },
  { id: 'dead', title: 'Dead' },
  { id: 'follow-up', title: 'Follow-up' },
];
